# SPDX-FileCopyrightText: 2023 Charles Crighton <rockwren@crighton.nz>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
    (?x)^(
        rockwren/jsondb_test.py|
        rockwren/utils_test.py|
        rockwren/fqdn_test.py
    )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files
- repo: https://github.com/fsfe/reuse-tool
  rev: v2.1.0
  hooks:
  - id: reuse
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.2
  hooks:
  - id: autopep8
- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.10.0
  hooks:
  - id: reorder-python-imports
    exclude: |
      (?x)^(
          rockwren/accesspoint.py |
          rockwren/mqtt_client.py |
          rockwren/rockwren.py
      )$
